# Site settings
title: Daniel Melo Ramos - Blog
description: A blog about me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielmeloramos.com.br" # the base hostname & protocol for your site e.g. 
# url: "http://localhost:3000" # the base hostname & protocol for your site e.g. 

# User settings
username: Daniel Melo Ramos
user_description: Desenvolvido por <b>Daniel Melo Ramos</b>, que vive no Brasil, construindo coisas úteis para o mundo.
email: meloramosdaniel@gmail.com
github_username: "danielmeloramos"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Séries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre Mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
