# Site settings
title: Daniel Melo Ramos - Blog
description: A blog about me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielmeloramos.com.br" # the base hostname & protocol for your site e.g. 

# User settings
username: Daniel Melo Ramos
user_description: Desenvolvido por <b>Daniel Melo Ramos</b>, que vive no Brasil, construindo coisas úteis para o mundo.
email: meloramosdaniel@gmail.com
github: "danielmeloramos"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
